server {
    listen 80;
    
    # จำกัดขนาดไฟล์อัปโหลด 10MB
    client_max_body_size 10M;

    location / {
        proxy_pass http://app_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

upstream app_servers {
    server app:8000;
}